=begin comment

mb-mail-service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package MailService::CratesendApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use MailService::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'MailService::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = MailService::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# send_mail_bulk_route
#
# 
#
# @param ARRAY[SendItem] $send_item  (required)
{
    my $params = {
    'send_item' => {
        data_type => 'ARRAY[SendItem]',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'send_mail_bulk_route' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[SendResponse]',
        };
}
# @return ARRAY[SendResponse]
#
sub send_mail_bulk_route {
    my ($self, %args) = @_;

    # verify the required parameter 'send_item' is set
    unless (exists $args{'send_item'}) {
      croak("Missing the required parameter 'send_item' when calling send_mail_bulk_route");
    }

    # parse inputs
    my $_resource_path = '/send_bulk';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'send_item'}) {
        $_body_data = $args{'send_item'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[SendResponse]', $response);
    return $_response_object;
}

#
# send_mail_route
#
# 
#
# @param SendItem $send_item  (required)
{
    my $params = {
    'send_item' => {
        data_type => 'SendItem',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'send_mail_route' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub send_mail_route {
    my ($self, %args) = @_;

    # verify the required parameter 'send_item' is set
    unless (exists $args{'send_item'}) {
      croak("Missing the required parameter 'send_item' when calling send_mail_route");
    }

    # parse inputs
    my $_resource_path = '/send_single';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'send_item'}) {
        $_body_data = $args{'send_item'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

1;
