=begin comment

mb-mail-service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('MailService::CraterenderApi');

my $api = MailService::CraterenderApi->new();
isa_ok($api, 'MailService::CraterenderApi');

#
# render_html_route_get test
#
# uncomment below and update the test
#my $render_html_route_get_template_id = undef; # replace NULL with a proper value
#my $render_html_route_get_lang = undef; # replace NULL with a proper value
#my $render_html_route_get_result = $api->render_html_route_get(template_id => $render_html_route_get_template_id, lang => $render_html_route_get_lang);

#
# render_html_route_post test
#
# uncomment below and update the test
#my $render_html_route_post_template_id = undef; # replace NULL with a proper value
#my $render_html_route_post_body = undef; # replace NULL with a proper value
#my $render_html_route_post_lang = undef; # replace NULL with a proper value
#my $render_html_route_post_result = $api->render_html_route_post(template_id => $render_html_route_post_template_id, body => $render_html_route_post_body, lang => $render_html_route_post_lang);

#
# render_text_route_get test
#
# uncomment below and update the test
#my $render_text_route_get_template_id = undef; # replace NULL with a proper value
#my $render_text_route_get_lang = undef; # replace NULL with a proper value
#my $render_text_route_get_result = $api->render_text_route_get(template_id => $render_text_route_get_template_id, lang => $render_text_route_get_lang);

#
# render_text_route_post test
#
# uncomment below and update the test
#my $render_text_route_post_template_id = undef; # replace NULL with a proper value
#my $render_text_route_post_body = undef; # replace NULL with a proper value
#my $render_text_route_post_lang = undef; # replace NULL with a proper value
#my $render_text_route_post_result = $api->render_text_route_post(template_id => $render_text_route_post_template_id, body => $render_text_route_post_body, lang => $render_text_route_post_lang);


done_testing();
