=begin comment

mb-mail-service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('MailService::CrateApi');

my $api = MailService::CrateApi->new();
isa_ok($api, 'MailService::CrateApi');

#
# available_locales test
#
# uncomment below and update the test
#my $available_locales_result = $api->available_locales();

#
# healthcheck test
#
# uncomment below and update the test
#my $healthcheck_result = $api->healthcheck();


done_testing();
