=begin comment

mb-mail-service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by the OpenAPI Generator
# Please update the test cases below to test the model.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;


use_ok('MailService::Object::SendResponse');

# uncomment below and update the test
#my $instance = MailService::Object::SendResponse->new();
#
#isa_ok($instance, 'MailService::Object::SendResponse');


done_testing();
